sudo: false
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/eigen-eigen-5a0156e40feb
    - $HOME/boost_1_67_0

before_script:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2 -O - | tar -xj -C $HOME
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2 -O - | tar -xj -C $HOME
  - git clone https://github.com/AMatrix/AMatrix.git $HOME/AMatrix

script:
  - mkdir build
  - cd build
  - cmake .. -DEIGEN3_ROOT="$HOME/eigen-eigen-5a0156e40feb" -DBOOST_ROOT="$HOME/boost_1_67_0" -DAMATRIX_ROOT="$HOME/AMatrix"
  - cmake --build .
  - cd ..
  - ./build/test/run_tests
